### ISSUE TITLE
Add tests for new support for setting classloader for proxy building/demarshalling

### ISSUE THREAD

**Issue by zachmccormick** [VT-Magnum-Research/sodacloud#2]

**Comment by zachmccormick** [comment]
It passes the current tests, so I'm pretty confident that I haven't caused any problems, but to be safe I need to add a small battery of tests to make sure this works.

**Comment by hamiltont** [comment]
Sure. BTW, you have direct push access to the repository, so there is no
need to go through the pull request system unless you just want to notify
everyone of changes
